---
- hosts: builder.octo-emerging.redhataicoe.com
  become: true
  gather_facts: true
  collections:
    - containers.podman
  tasks:
  - name: install podman
    package:
      name: podman
      state: present

  - name: Clone the application repo
    git:
      repo: "{{ repo }}"

  - name: build the containerfile
    containers.podman.podman_image:
      name: bootc
      push: true
      push_args:
        dest: "{{ registry }}/{{ image }}"