---
- hosts: builder.octo-emerging.redhataicoe.com
  become: true
  gather_facts: true
  remote_user: ec2-user
  collections:
    - containers.podman
  tasks:
  - name: Clone the application repo
    git:
      repo: "{{ repo }}"
      dest: "/tmp/app"
    register: clone

  - name: build the containerfile
    containers.podman.podman_image:
      name: "{{ appName}}"
      path: "/tmp/app/{{ path }}"
      build:
        extra_args: "--build-arg sshpubkey=cat $(cat ~/.ssh/id_rsa.pub)"
      push: true
      push_args:
        dest: "{{ registry }}/{{ image }}/{{ appName }}:latest"

  - name: set the image tag
    set_stats:
      data:
        pushed_image: "{{ registry }}/{{ image }}/{{ appName }}:latest"
        revision: "{{ clone.after }}"

  - name: clean up the image
    containers.podman.podman_image:
      name: "{{ item }}"
      state: absent
    with_items:
      - "{{ registry }}/{{ image }}/{{ appName }}:latest"
      - "localhost/{{ appName }}:latest"
