---
- hosts: builder.octo-emerging.redhataicoe.com
  become: true
  gather_facts: true
  collections:
    - containers.podman
  tasks:
  - name: install podman
    package:
      name: podman
      state: present

  - name: Clone the application repo
    git:
      repo: "{{ repo }}"
      dest: "/tmp/app"

  - name: build the containerfile
    containers.podman.podman_image:
      name: "{{ appName}}"
      path: "/tmp/app/{{ path }}"
      build:
        extra_args: "--build-arg sshpubkey={{ pubKey}}"
      push: true
      push_args:
        dest: "{{ registry }}/{{ image }}/{{ appName }}:latest"

  - name: set the image tag
    set_stats:
      image: "{{ registry }}/{{ image }}/{{ appName }}:latest"