---
- hosts: builder.octo-emerging.redhataicoe.com
  become: true
  remote_user: ec2-user
  gather_facts: true
  collections:
    - containers.podman
  tasks:
  - name: Clone the application repo
    git:
      repo: "{{ repo }}"
      dest: "/tmp/bootc"
    register: clone

  - name: debug public key
    debug:
      var: PUBKEY

  - name: Generate the application bootc image
    containers.podman.podman_image:
      name: "{{ appName}}"
      build:
        extra_args: "--build-arg 'sshpubkey={{ PUBKEY }}'"
        file: "Containerfile"
      path: "/tmp/bootc/{{ path }}"
      push: true
      push_args:
        dest: "{{ registry }}/{{ image }}"

  - name: set the image tag
    set_stats:
      data:
        pushed_image: "{{ registry }}/{{ image }}/{{ appName }}:latest"
        revision: "{{ clone.after }}"

  - name: clean up the image
    containers.podman.podman_image:
      name: "{{ item }}"
      state: absent
    with_items:
      - "{{ registry }}/{{ image }}/{{ appName }}:latest"
      - "localhost/{{ appName }}:latest"
