---
- hosts: localhost
  become: false
  collections:
    - containers.podman
  tasks:
  - name: ensure podman is installed
    package:
      name: podman
      state: present

  - name: podman build ami
    containers.podman.podman_container:
      name: myapplication
      image: quay.io/centos-bootc/bootc-image-builder:latest
      state: started
      privileged: true
      restart: false
      restart_policy: "no"
      command: ["--type", "ami", "--aws-ami-name", "centos-bootc-x86-rc", "--aws-bucket", "somaltest", "--aws-region", "us-east-1", "--target-arch", "x86_64", "quay.io/rcook/useradd:latest"]
      volumes:
      - /Users/rcook/.aws:/root/.aws
