---
- hosts: 35.175.191.132
  become: false
  collections:
    - containers.podman
  tasks:
  - name: install podman
    package:
      name: podman
      state: present

  - name: run the build in a kubernetes pod
    containers.podman.podman_play:
      kube_file: podman_os_play.yaml
      state: started