---
apiVersion: v1
kind: Pod
metadata:
  name: podman
spec:
  containers:
  - name: osbuild
    securityContext:
      privileged: true
      capabilities:
        add:
          - SYS_CHROOT
          - SETFCAP
          - SETGID
          - SETUID
          - SYS_ADMIN
        selinuxOptions:
          type: spc_t
    image: quay.io/rcook/bootc:latest
    restartPolicy: Never
    command: ["--type", "ami", "--aws-ami-name", "centos-bootc-x86-rc", "--aws-bucket", "somaltest", "--aws-region", "us-east-1", "--target-arch", "x86_64", "quay.io/rcook/useradd:latest"]