---
- hosts: builder.octo-emerging.redhataicoe.com
  remote_user: ec2-user
  become: true
  collections:
    - containers.podman
  tasks:
  - name: Clone the application repo
    git:
      repo: "{{ repo }}"
      dest: "/tmp/app"
    register: clone

  - name: build the containerfile
    containers.podman.podman_image:
      name: "{{ appName}}:{{ clone.after }}"
      build:
        file: "/tmp/app/{{ path }}/{{ app_path }}/Containerfile"
      path: "/tmp/app/{{ path }}/{{ app_path }}"
      push: true
      push_args:
        dest: "{{ registry }}/{{ image }}"

  - name: make the directory for quadlets
    ansible.builtin.file:
      path: "/tmp/app/{{ path }}/bootc/build"
      state: directory

  - name: Clone the application repo
    git:
      repo: "{{ repo }}"
      dest: "/tmp/app"
    delegate_to: localhost
    become: false

  - name: Template files
    template:
      src: "{{ item }}"
      dest: "/tmp/app/{{ path }}/bootc/build/{{ item | basename | replace('.j2', '') }}"
      mode: '0644'
    with_fileglob:
    - "/tmp/app/{{ path }}/bootc/ansible-templates/*"

  - name: Generate the application bootc image
    containers.podman.podman_image:
      name: "bootc-{{ appName}}:{{ clone.after }}"
      build:
        file: "Containerfile"
      path: "/tmp/app/{{ path }}/bootc"
      push: true
      push_args:
        dest: "{{ registry }}/{{ image }}"

  - name: tag images as latest
    containers.podman.podman_tag:
      image: "localhost/{{ appName }}:{{ clone.after }}"
      target_names: "{{ registry }}/{{ image }}/{{ appName }}:latest"

  - name: tag images as latest
    containers.podman.podman_tag:
      image: "localhost/bootc-{{ appName }}:{{ clone.after }}"
      target_names: "{{ registry }}/{{ image }}/bootc-{{ appName }}:latest"

  - name: push the two new tagged images
    containers.podman.podman_image:
      name: "{{ item }}"
      push: true
    with_items:
      - "{{ registry }}/{{ image }}/{{ appName }}:latest"
      - "{{ registry }}/{{ image }}/bootc-{{ appName }}:latest"

  - name: clean up the image
    containers.podman.podman_image:
      name: "{{ item }}"
      state: absent
    with_items:
      - "{{ registry }}/{{ image }}/{{ appName }}:{{ clone.after }}"
      - "localhost/{{ appName }}:latest"
      - "localhost/bootc-{{ appName }}:latest"
      - "{{ registry }}/{{ image }}/bootc-{{ appName }}:{{ clone.after }}"
      - "{{ registry }}/{{ image }}/{{ appName }}:latest"
      - "{{ registry }}/{{ image }}/bootc-{{ appName }}:latest"

  - name: delete the cloned directory
    ansible.builtin.file:
      path: "/tmp/app"
      state: absent

  - name: pass the revision and image to the next job
    set_stats:
      data:
        revision: "{{ clone.after }}"
        pushed_image: "{{ registry }}/{{ image }}/bootc-{{ appName }}:{{ clone.after }}"
