---
- hosts: builder.octo-emerging.redhataicoe.com
  become: false
  gather_facts: false
  remote_user: ec2-user
  collections:
    - containers.podman
  tasks:
  - name: Clone the application repo
    git:
      repo: "{{ repo }}"
      dest: "/tmp/app"
    register: clone

  - name: build the containerfile
    containers.podman.podman_image:
      name: "{{ appName}}:{{ clone.after }}"
      build:
        file: "/tmp/app/{{ path }}/Containerfile"
      path: "/tmp/app/{{ path }}"
      push: true
      push_args:
        dest: "{{ registry }}/{{ image }}"

  - name: make the directory for quadlets
    ansible.builtin.file:
      path: "/tmp/app/{{ path }}/bootc/build"
      state: directory

  - name: modify the template in the ansible-templates directory to include the new image
    ansible.builtin.template:
      src: "/tmp/app/{{ path }}recipes/natural_language_processing/chatbot/bootc/ansible-templates/chatbot.image.j2"
      dest: "/tmp/app/{{ path }}/recipes/natural_language_processing/chatbot/bootc/build/chatbot.image"
      mode: 0644
      vars:
        appName: "{{ appName }}"
        image: "{{ image }}"
        registry: "{{ registry }}"
        revision: "{{ clone.after }}"

  - name: modify the template in the ansible-templates directory to include the new image
    ansible.builtin.template:
      src: "/tmp/app/{{ path }}recipes/natural_language_processing/chatbot/bootc/ansible-templates/chatbot.kube.j2"
      dest: "/tmp/app/{{ path }}/recipes/natural_language_processing/chatbot/bootc/build/chatbot.kube"
      mode: 0644
      vars:
        appName: "{{ appName }}"
        image: "{{ image }}"
        registry: "{{ registry }}"
        revision: "{{ clone.after }}"

  - name: modify the template in the ansible-templates directory to include the new image
    ansible.builtin.template:
      src: "/tmp/app/{{ path }}recipes/natural_language_processing/chatbot/bootc/ansible-templates/chatbot.yaml.j2"
      dest: "/tmp/app/{{ path }}/recipes/natural_language_processing/chatbot/bootc/build/chatbot.yaml"
      mode: 0644
      vars:
        appName: "{{ appName }}"
        image: "{{ image }}"
        registry: "{{ registry }}"
        revision: "{{ clone.after }}"

  - name: Generate the application bootc image
    containers.podman.podman_image:
      name: "bootc-{{ appName}}:{{ clone.after }}"
      build:
        file: "quadlet-Containerfile"
      path: "/tmp/app/{{ path }}"
      push: true
      push_args:
        dest: "{{ registry }}/{{ image }}"

  - name: tag images as latest
    containers.podman.podman_tag:
      image: "localhost/{{ appName }}:{{ clone.after }}"
      target_names: "{{ registry }}/{{ image }}/{{ appName }}:latest"

  - name: tag images as latest
    containers.podman.podman_tag:
      image: "localhost/bootc-{{ appName }}:{{ clone.after }}"
      target_names: "{{ registry }}/{{ image }}/bootc-{{ appName }}:latest"

  - name: clean up the image
    containers.podman.podman_image:
      name: "{{ item }}"
      state: absent
    with_items:
      - "{{ registry }}/{{ image }}/{{ appName }}:{{ clone.after }}"
      - "localhost/{{ appName }}:latest"
      - "localhost/bootc-{{ appName }}:latest"
      - "{{ registry }}/{{ image }}/bootc-{{ appName }}:{{ clone.after }}"
      - "{{ registry }}/{{ image }}/{{ appName }}:latest"
      - "{{ registry }}/{{ image }}/bootc-{{ appName }}:latest"

  - name: delete the cloned directory
    ansible.builtin.file:
      path: "/tmp/app"
      state: absent

  - name: pass the revision and image to the next job
    set_stats:
      data:
        revision: "{{ clone.after }}"
        pushed_image: "{{ registry }}/{{ image }}/bootc-{{ appName }}:{{ clone.after }}"
