---
- hosts: edge
  become: true
  gather_facts: true
  tasks:
  - name: trigger bootc swap if image was updated
    command: "bootc upgrade --apply"
    when: image_pull.changed

  - name: reboot if image was updated
    command: "reboot"
    when: image_pull.changed