---
- hosts: 54.80.184.99
  become: true
  gather_facts: true
  tasks:
  - name: trigger bootc upgrade if image was updated
    command: "bootc upgrade --apply"

  - name: reboot if image was updated
    command: "reboot"
    when: image_pull.changed
