---
- hosts: 54.236.49.68
  become: true
  gather_facts: true
  tasks:
  - name: Upgrade bootc
    bootc_upgrade:
      apply: true
    register: result

  - name: Reboot the system
    ansible.builtin.reboot:
    when: result.changed

