---
- hosts: edge
  become: true
  gather_facts: true
  tasks:
  - name: pull the latest bootc image using podman
    containers.podman.podman_image:
      name: "{{ image }}"
      pull: true
    register: image_pull

  - name: trigger bootc swap if image was updated
    command: "bootc switch {{ image }}"
    when: image_pull.changed